export interface History {
    _id: string,
    firstName: string,
    lastName: string,
    position: string,
    learningGroup: string,
    subjectTeach: string,
    reason: string,
    objective: string,
    typeEquipments: string,
    learningGroups: string,
    majorList: string,
    budget: number,
    necessary: number,
    existEquipment: number,
    otherReason: string,
    dateProject: Date,
    condition: string,
    status: string,
    approveCondition: string,
    approveReason: string,
    creator: string
}
